@startuml SIIL_User_Management_Use_Case_Final

left to right direction
skinparam packageStyle rectangle
actor "Utilisateur" as U
actor "Administrateur" as A

package "Système de Gestion des Utilisateurs" {
    usecase "Consulter Profil" as ViewProfile
    usecase "Modifier Profil Utilisateur" as ModifyUserProfile

    usecase "Demande de réinitialiser Mot de Passe Utilisateur" as ResetUserPW
    usecase "Créer Profil Utilisateur" as CreateUser
    usecase "Modifier Profil Autre Utilisateur" as ModifyOtherUser
    usecase "Supprimer Profil Utilisateur" as DeleteUser
    usecase "Consulter Liste Utilisateurs" as ViewUsers

    U -- ViewProfile


    A -- CreateUser

    A -- ViewUsers

    ViewProfile <.. ModifyUserProfile : <<extend>>



    ViewUsers <.. ModifyOtherUser : <<extend>>
    ViewUsers <.. DeleteUser : <<extend>>
        ViewUsers <.. ResetUserPW : <<extend>>
}

@enduml
